### ISSUE TITLE
Readme problem..... request for more screenshots -  💖 the one you have now!

### ISSUE THREAD

**Issue by PySimpleGUI** [Project-VULMA/bi-vulma#9]
![image](https://user-images.githubusercontent.com/46163555/132553727-c9d3ec01-8334-467e-86a8-dea47c06bb69.png)

It looks like there's a problem with the badges at the top of your readme.  I can see things are still new and in-process so you probably already know these things.

I like that you took the rare step of including a screenshot!  VERY NICE!!

I peeked in your code and was surprised so see you've got more than one window!!  I want to see those too!!  (please)

Was excited to see what you've made so far.  Very motivating to see work like yours on GitHub.  Keep building the cool stuff you're making!!  It has an impact.

**Comment by anhelus** [comment]
Sorry to reply you this late, I was very busy during this period. However, I'll fix this as soon as possible.
